# main menu
[[main]]
name = "Inicio"
url = ""
weight = 1

[[main]]
name = "Nosotros"
url = "about/"
weight = 2

[[main]]
name = "Blog"
url = "blog/"
weight = 3

[[main]]
weight = 4
name = "Páginas"
hasChildren = true

  [[main]]
  parent = "Páginas"
  name = "Última públicación"
  url = "blog/post-1/"
  weight = 1

  [[main]]
  parent = "Páginas"
  name = "Términos & Condiciones"
  url = "terms-and-conditions/"
  weight = 7
  
[[main]]
name = "Contacto"
url = "contact/"
weight = 5


# footer menu
[[footer]]
name = "Acerca"
url = "about/"
weight = 1

[[footer]]
name = "Blog"
url = "blog/"
weight = 2

[[footer]]
name = "Términos & Condiciones"
url = "terms-and-conditions/"
weight = 4